# Read about factories at https://github.com/thoughtbot/factory_girl

FactoryGirl.define do
  factory :transport_canada_registration do
    accesscode "MyString"
    logger_partvin "MyString"
    callresult "MyString"
    l_type "MyString"
    batch "MyString"
    province "MyString"
    preflanguage "MyString"
    start_date "2012-09-04 16:22:43"
    end_date "2012-09-04 16:22:43"
    firstname "MyString"
    lastname "MyString"
    phonenumber "MyString"
    e_mailaddress "MyString"
    number "MyString"
    street "MyString"
    city "MyString"
    postalcode "MyString"
    vehicle "MyString"
    vin "MyString"
    province "MyString"
    havevehicle "MyString"
    whynot "MyString"
    since_day "MyString"
    since_month "MyString"
    since_year "MyString"
    name_2 "MyString"
    gender_2 "MyString"
    yob_2 "MyString"
    name_3 "MyString"
    gender_3 "MyString"
    yob_3 "MyString"
    name_4 "MyString"
    gender_4 "MyString"
    yob_4 "MyString"
    name_5 "MyString"
    gender_5 "MyString"
    yob_5 "MyString"
    name_6 "MyString"
    gender_6 "MyString"
    yob_6 "MyString"
    age_range_2 "MyString"
    age_range_3 "MyString"
    age_range_4 "MyString"
    age_range_5 "MyString"
    age_range_6 "MyString"
    yearofbirthanswered "MyString"
    age "MyString"
    agerange "MyString"
    gender "MyString"
    typeoffuel "MyString"
    transmission "MyString"
    completedonline "MyString"
    finalstatus "MyString"
    logger_id 1
    assigndate "2012-09-04 16:22:43"
    returndate "2012-09-04 16:22:43"
  end
end
