require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OttoViewRawTripsController do

  # This should return the minimal set of attributes required to create a valid
  # OttoViewRawTrip. As you add validations to OttoViewRawTrip, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OttoViewRawTripsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all otto_view_raw_trips as @otto_view_raw_trips" do
      otto_view_raw_trip = OttoViewRawTrip.create! valid_attributes
      get :index, {}, valid_session
      assigns(:otto_view_raw_trips).should eq([otto_view_raw_trip])
    end
  end

  describe "GET show" do
    it "assigns the requested otto_view_raw_trip as @otto_view_raw_trip" do
      otto_view_raw_trip = OttoViewRawTrip.create! valid_attributes
      get :show, {:id => otto_view_raw_trip.to_param}, valid_session
      assigns(:otto_view_raw_trip).should eq(otto_view_raw_trip)
    end
  end

  describe "GET new" do
    it "assigns a new otto_view_raw_trip as @otto_view_raw_trip" do
      get :new, {}, valid_session
      assigns(:otto_view_raw_trip).should be_a_new(OttoViewRawTrip)
    end
  end

  describe "GET edit" do
    it "assigns the requested otto_view_raw_trip as @otto_view_raw_trip" do
      otto_view_raw_trip = OttoViewRawTrip.create! valid_attributes
      get :edit, {:id => otto_view_raw_trip.to_param}, valid_session
      assigns(:otto_view_raw_trip).should eq(otto_view_raw_trip)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OttoViewRawTrip" do
        expect {
          post :create, {:otto_view_raw_trip => valid_attributes}, valid_session
        }.to change(OttoViewRawTrip, :count).by(1)
      end

      it "assigns a newly created otto_view_raw_trip as @otto_view_raw_trip" do
        post :create, {:otto_view_raw_trip => valid_attributes}, valid_session
        assigns(:otto_view_raw_trip).should be_a(OttoViewRawTrip)
        assigns(:otto_view_raw_trip).should be_persisted
      end

      it "redirects to the created otto_view_raw_trip" do
        post :create, {:otto_view_raw_trip => valid_attributes}, valid_session
        response.should redirect_to(OttoViewRawTrip.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved otto_view_raw_trip as @otto_view_raw_trip" do
        # Trigger the behavior that occurs when invalid params are submitted
        OttoViewRawTrip.any_instance.stub(:save).and_return(false)
        post :create, {:otto_view_raw_trip => {}}, valid_session
        assigns(:otto_view_raw_trip).should be_a_new(OttoViewRawTrip)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OttoViewRawTrip.any_instance.stub(:save).and_return(false)
        post :create, {:otto_view_raw_trip => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested otto_view_raw_trip" do
        otto_view_raw_trip = OttoViewRawTrip.create! valid_attributes
        # Assuming there are no other otto_view_raw_trips in the database, this
        # specifies that the OttoViewRawTrip created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OttoViewRawTrip.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => otto_view_raw_trip.to_param, :otto_view_raw_trip => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested otto_view_raw_trip as @otto_view_raw_trip" do
        otto_view_raw_trip = OttoViewRawTrip.create! valid_attributes
        put :update, {:id => otto_view_raw_trip.to_param, :otto_view_raw_trip => valid_attributes}, valid_session
        assigns(:otto_view_raw_trip).should eq(otto_view_raw_trip)
      end

      it "redirects to the otto_view_raw_trip" do
        otto_view_raw_trip = OttoViewRawTrip.create! valid_attributes
        put :update, {:id => otto_view_raw_trip.to_param, :otto_view_raw_trip => valid_attributes}, valid_session
        response.should redirect_to(otto_view_raw_trip)
      end
    end

    describe "with invalid params" do
      it "assigns the otto_view_raw_trip as @otto_view_raw_trip" do
        otto_view_raw_trip = OttoViewRawTrip.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OttoViewRawTrip.any_instance.stub(:save).and_return(false)
        put :update, {:id => otto_view_raw_trip.to_param, :otto_view_raw_trip => {}}, valid_session
        assigns(:otto_view_raw_trip).should eq(otto_view_raw_trip)
      end

      it "re-renders the 'edit' template" do
        otto_view_raw_trip = OttoViewRawTrip.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OttoViewRawTrip.any_instance.stub(:save).and_return(false)
        put :update, {:id => otto_view_raw_trip.to_param, :otto_view_raw_trip => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested otto_view_raw_trip" do
      otto_view_raw_trip = OttoViewRawTrip.create! valid_attributes
      expect {
        delete :destroy, {:id => otto_view_raw_trip.to_param}, valid_session
      }.to change(OttoViewRawTrip, :count).by(-1)
    end

    it "redirects to the otto_view_raw_trips list" do
      otto_view_raw_trip = OttoViewRawTrip.create! valid_attributes
      delete :destroy, {:id => otto_view_raw_trip.to_param}, valid_session
      response.should redirect_to(otto_view_raw_trips_url)
    end
  end

end
