require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TransportCanadaRegistrationsController do

  # This should return the minimal set of attributes required to create a valid
  # TransportCanadaRegistration. As you add validations to TransportCanadaRegistration, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TransportCanadaRegistrationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all transport_canada_registrations as @transport_canada_registrations" do
      transport_canada_registration = TransportCanadaRegistration.create! valid_attributes
      get :index, {}, valid_session
      assigns(:transport_canada_registrations).should eq([transport_canada_registration])
    end
  end

  describe "GET show" do
    it "assigns the requested transport_canada_registration as @transport_canada_registration" do
      transport_canada_registration = TransportCanadaRegistration.create! valid_attributes
      get :show, {:id => transport_canada_registration.to_param}, valid_session
      assigns(:transport_canada_registration).should eq(transport_canada_registration)
    end
  end

  describe "GET new" do
    it "assigns a new transport_canada_registration as @transport_canada_registration" do
      get :new, {}, valid_session
      assigns(:transport_canada_registration).should be_a_new(TransportCanadaRegistration)
    end
  end

  describe "GET edit" do
    it "assigns the requested transport_canada_registration as @transport_canada_registration" do
      transport_canada_registration = TransportCanadaRegistration.create! valid_attributes
      get :edit, {:id => transport_canada_registration.to_param}, valid_session
      assigns(:transport_canada_registration).should eq(transport_canada_registration)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TransportCanadaRegistration" do
        expect {
          post :create, {:transport_canada_registration => valid_attributes}, valid_session
        }.to change(TransportCanadaRegistration, :count).by(1)
      end

      it "assigns a newly created transport_canada_registration as @transport_canada_registration" do
        post :create, {:transport_canada_registration => valid_attributes}, valid_session
        assigns(:transport_canada_registration).should be_a(TransportCanadaRegistration)
        assigns(:transport_canada_registration).should be_persisted
      end

      it "redirects to the created transport_canada_registration" do
        post :create, {:transport_canada_registration => valid_attributes}, valid_session
        response.should redirect_to(TransportCanadaRegistration.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved transport_canada_registration as @transport_canada_registration" do
        # Trigger the behavior that occurs when invalid params are submitted
        TransportCanadaRegistration.any_instance.stub(:save).and_return(false)
        post :create, {:transport_canada_registration => {}}, valid_session
        assigns(:transport_canada_registration).should be_a_new(TransportCanadaRegistration)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TransportCanadaRegistration.any_instance.stub(:save).and_return(false)
        post :create, {:transport_canada_registration => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested transport_canada_registration" do
        transport_canada_registration = TransportCanadaRegistration.create! valid_attributes
        # Assuming there are no other transport_canada_registrations in the database, this
        # specifies that the TransportCanadaRegistration created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TransportCanadaRegistration.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => transport_canada_registration.to_param, :transport_canada_registration => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested transport_canada_registration as @transport_canada_registration" do
        transport_canada_registration = TransportCanadaRegistration.create! valid_attributes
        put :update, {:id => transport_canada_registration.to_param, :transport_canada_registration => valid_attributes}, valid_session
        assigns(:transport_canada_registration).should eq(transport_canada_registration)
      end

      it "redirects to the transport_canada_registration" do
        transport_canada_registration = TransportCanadaRegistration.create! valid_attributes
        put :update, {:id => transport_canada_registration.to_param, :transport_canada_registration => valid_attributes}, valid_session
        response.should redirect_to(transport_canada_registration)
      end
    end

    describe "with invalid params" do
      it "assigns the transport_canada_registration as @transport_canada_registration" do
        transport_canada_registration = TransportCanadaRegistration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TransportCanadaRegistration.any_instance.stub(:save).and_return(false)
        put :update, {:id => transport_canada_registration.to_param, :transport_canada_registration => {}}, valid_session
        assigns(:transport_canada_registration).should eq(transport_canada_registration)
      end

      it "re-renders the 'edit' template" do
        transport_canada_registration = TransportCanadaRegistration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TransportCanadaRegistration.any_instance.stub(:save).and_return(false)
        put :update, {:id => transport_canada_registration.to_param, :transport_canada_registration => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested transport_canada_registration" do
      transport_canada_registration = TransportCanadaRegistration.create! valid_attributes
      expect {
        delete :destroy, {:id => transport_canada_registration.to_param}, valid_session
      }.to change(TransportCanadaRegistration, :count).by(-1)
    end

    it "redirects to the transport_canada_registrations list" do
      transport_canada_registration = TransportCanadaRegistration.create! valid_attributes
      delete :destroy, {:id => transport_canada_registration.to_param}, valid_session
      response.should redirect_to(transport_canada_registrations_url)
    end
  end

end
